### ISSUE TITLE
Conversion of large decimal fails with an unrelated error messages

### ISSUE THREAD

**Issue by sanjmeh** [kbroman/broman#10]
The function `convert2hex` fails with the following error message that is terribly confusing. Best will be to give a message that large numbers not supported.

```Error in if (is.double(x) && all(is.na(x) | x == as.integer(x))) x <- as.integer(x) : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In as.hexmode(d) : NAs introduced by coercion to integer range
```

**Comment by kbroman** [comment]
Here are some examples:

```r
dec2hex(2.1e9)
# [1] "7d2b7500"

dec2hex(2.2e9)
# Error in if (is.double(x) && all(is.na(x) | x == as.integer(x))) x <- as.integer(x) : 
#  missing value where TRUE/FALSE needed
# In addition: Warning message:
# In as.hexmode(d) : NAs introduced by coercion to integer range

hex2dec("7d2b7500")
# [1] 2100000000

hex2dec("8d2b7500")
# [1] NA
```

**Comment by kbroman** [comment]
Largest allowable value is 2^{31} - 1; must be related to the largest int.

```r
dec2hex(2^31L-1L)
# [1] "7fffffff"

dec2hex(2^31L)
# Error in if (is.double(x) && all(is.na(x) | x == as.integer(x))) x <- as.integer(x) : 
#   missing value where TRUE/FALSE needed
# In addition: Warning message:
# In as.hexmode(d) : NAs introduced by coercion to integer range

hex2dec("7fffffff")
# [1] 2147483647

hex2dec("80000000")
# [1] NA
```

**Comment by kbroman** [comment]
dec2hex / convert2hex now giving warning, and added to the documentation.

**Comment by sanjmeh** [comment]
That's so nice you changed the error message. Might save hours of frustration for others. Thanks.
Any chance of ever getting larger numbers supported in here? Actually I know the `gmp` package supports it but the package is unstable on mac as the function `as_bigz` crashes R every time.

**Comment by kbroman** [comment]
The [code for this function](https://github.com/kbroman/broman/blob/master/R/convert2hex.R#L31) is simply

```r
as.character(as.hexmode(d))
```

It's simply for convenience; I'm not likely to put more effort into it.
